name: test and lint
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Run tests
        run: ruby test/fizz_buzz_test.rb
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Install dependencies
        run: bundle install
      - name: Run lint
        run: bundle exec rubocop
  success_notify:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
    - name: slack notify
      # run: |
      #   echo ${{ github.actor }}
      #   echo ${{ github.repository }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: times_だいそん
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: いえーい
        SLACK_TITLE: ふぉ〜〜〜
        SLACK_USERNAME: レビューBot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  failure_notify:
    if: failure()
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
    - name: slack notify
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: times_だいそん
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: アウト
        SLACK_TITLE: だいそん
        SLACK_USERNAME: レビューBot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}