name: test and lint
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Run tests
        run: ruby test/fizz_buzz_test.rb
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Install dependencies
        run: bundle install
      - name: Run lint
        run: bundle exec rubocop
  success_notify:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
    - name: slack notify
      run: echo ${{ github.actor }}
      run: echo ${{ github.repository }}
      # uses: rtCamp/action-slack-notify@v2.1.3
      # env:
      #   SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #   SLACK_MESSAGE: 'Post Content :rocket:'
      #   SLACK_CHANNEL: ci