name: test and lint
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run tests
        run: ruby test/fizz_buzz_test.rb
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install dependencies
        run: bundle install
      - name: Run lint
        run: bundle exec rubocop